[package]
name = "civ-sim"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.24"
clap = { version = "4.2.5", features = ["derive"] }
image = "0.24.6"
noise = "0.8.2"
rand = "0.8.5"
rayon = "1.8.0"
